---
- name: Voeg gebruiker 'demo' toe
  user:
    name: demo
    comment: Demo gebruiker
    shell: /bin/bash
    create_home: yes
    state: present

- name: Voeg 'demo' toe aan sudoers (optioneel)
  copy:
    dest: /etc/sudoers.d/demo
    content: "demo ALL=(ALL) NOPASSWD:ALL\n"
    mode: 0440
  when: add_sudo is defined and add_sudo

- name: Voeg SSH-key toe voor gebruiker 'demo'
  authorized_key:
    user: demo
    key: "{{ lookup('file', 'roles/user/files/demo_id_rsa.pub') }}"
  when: add_ssh_key is defined and add_ssh_key
