CREATE TABLE IF NOT EXISTS public.ktb_pcdata (
  perceelid BIGINT PRIMARY KEY,
  perceeltype VARCHAR(15),
  huisnr INTEGER,
  huisnr_bag_letter VARCHAR(1),
  huisnr_bag_toevoeging VARCHAR(4),
  bag_nummeraanduidingid VARCHAR(16),
  bag_adresseerbaarobjectid VARCHAR(16),
  breedtegraad NUMERIC(12,8),
  lengtegraad NUMERIC(12,8),
  rdx NUMERIC(12,4),
  rdy NUMERIC(12,4),
  oppervlakte NUMERIC(12,0),
  gebruiksdoel VARCHAR(255),
  reeksid INTEGER,
  wijkcode VARCHAR(4),
  lettercombinatie VARCHAR(2),
  huisnr_van INTEGER,
  huisnr_tm INTEGER,
  reeksindicatie VARCHAR(1),
  straatid INTEGER,
  straatnaam VARCHAR(80),
  straatnaam_nen VARCHAR(24),
  plaatsid INTEGER,
  plaatsnaam VARCHAR(80),
  plaatsnaam_nen VARCHAR(24),
  plaatscode VARCHAR(4),
  gemeenteid INTEGER,
  gemeentenaam VARCHAR(80),
  gemeentenaam_nen VARCHAR(24),
  gemeentecode VARCHAR(4),
  cebucocode VARCHAR(3),
  provinciecode VARCHAR(1),
  provincienaam VARCHAR(20),
  CONSTRAINT chk_perceeltype    CHECK (perceeltype IN ('verblijfsobject','ligplaats','standplaats','postbus')),
  CONSTRAINT chk_reeksindicatie CHECK (reeksindicatie IN ('0','1'))
);

