---
# roles/btop/tasks/main.yml

- name: Install required packages for btop on Debian
  apt:
    name:
      - wget
      - tar
      - bzip2
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install required packages for btop on RedHat
  dnf:
    name:
      - wget
      - tar
      - bzip2
    state: present
  when: ansible_os_family == "RedHat"

- name: Create temporary directory for btop
  file:
    path: /tmp/btop
    state: directory
    mode: '0755'

- name: Download btop latest release (.tbz)
  get_url:
    url: https://github.com/aristocratos/btop/releases/latest/download/btop-x86_64-linux-musl.tbz
    dest: /tmp/btop/btop.tbz
    mode: '0644'

- name: Extract btop archive
  unarchive:
    src: /tmp/btop/btop.tbz
    dest: /tmp/btop/
    remote_src: yes
    extra_opts: [--bzip2]

- name: Run install.sh script from btop
  command: ./install.sh
  args:
    chdir: /tmp/btop/btop
- name: Fail if install.sh does not exist
  stat:
    path: /tmp/btop/btop/install.sh
  register: install_script

- name: Abort if install.sh is missing
  fail:
    msg: "install.sh script is missing!"
  when: not install_script.stat.exists

- name: Verify btop installation
  command: btop --version
  register: btop_version
  ignore_errors: true

- name: Show btop version
  debug:
    var: btop_version.stdout

